/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaJuntarComandas.java
 *
 * Created on 19/10/2010, 15:05:39
 */
package sigeve;

import org.jdesktop.application.Action;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JList;

/**
 *
 * @author Paulo Henrique
 */
public class TelaJuntarComandas
    extends javax.swing.JDialog
{
    private boolean uniaoRealizada = false;
    private DefaultComboBoxModel comboBoxModelDestino = new DefaultComboBoxModel();
    private DefaultListModel listModelComandas = new DefaultListModel();
    private DefaultListSelectionModel listSelModelComandas =
        new DefaultListSelectionModel()
        {
            /* JList com selectionMode=MULTIPLE_INTERVAL dispensando Ctrl
             * ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
             * Descr: Sobrescreve método de seleção dos itens.
             * Fonte: http://forums.sun.com/thread.jspa?threadID=5313897
             */
            @Override
            public void setSelectionInterval( int index0, int index1 )
            {
                if ( isSelectedIndex( index0 ) )
                {
                    super.removeSelectionInterval( index0, index1 );
                }
                else
                {
                    super.addSelectionInterval( index0, index1 );
                }
            }
        };
    private BancoDeDados bd;


    /** Creates new form TelaJuntarComandas
     *
     * @param parent
     * @param modal
     * @param bd
     */
    public TelaJuntarComandas( SigeveView parent, boolean modal, BancoDeDados bd )
    {
        super( parent.getFrame(), modal );
        initComponents();
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        this.bd = bd;

        carregarComandas();
    }

    private void carregarComandas()
    {
        try
        {
            String identificador;
            Comanda comandaAberta;
            Iterator<Comanda> it = bd.listarComandasAbertasBD().iterator();

            while ( it.hasNext() )
            {
                comandaAberta = it.next();
                identificador = comandaAberta.getPosicao() + ". " + comandaAberta.getNome();
                comboBoxModelDestino.addElement( identificador );
                //listModelComandas.addElement( identificador );
                listModelComandas.addElement( new CheckListItem( identificador ) );
            }
        }
        catch ( SQLException se )
        {
            Logger.getLogger( SigeveView.class.getName() ).log( Level.SEVERE, null, se );
        }
    }

    /**
     *
     */
    @Action
    public void cancelarUniao()
    {
        uniaoRealizada = false;
        dispose();
    }

    /**
     * asff
     */
    @Action
    public void confirmarUniao()
    {
        uniaoRealizada = true;
        dispose();
    }

    public boolean foiUniaoRealizada()
    {
        return uniaoRealizada;
    }

    public int getDestino()
    {
        Object o = jComboBoxDestino.getSelectedItem();
        String identificador;
        String strPosicao;

        if ( o instanceof String )
        {
            identificador = (String) o;
            // Ex.: "12. Paulo" --> "12":
            strPosicao = identificador.replaceFirst( "\\. .*", "");
            return Integer.parseInt( strPosicao );
        }
        // A linha seguinte não deverá ser acionada.
        else
            return 0;
    }

    /**
     * 
     * @return
     */
    public List<Integer> getPosicoes()
    {
        List<Integer> posicoes = new ArrayList<Integer>();
        Object[] objetos = jListComandas.getSelectedValues();
        CheckListItem cli;
        String identificador;
        String strPosicao;
        int posicao;

        for ( Object o : objetos)
        {
            if ( o instanceof CheckListItem )
            {
                cli = ( CheckListItem ) o;
                identificador = cli.toString();
                // Ex.: "12. Paulo" --> "12":
                strPosicao = identificador.replaceFirst( "\\. .*", "");
                posicao = Integer.parseInt( strPosicao );
                posicoes.add( posicao );
            }
        }
        return posicoes;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneComandas = new javax.swing.JScrollPane();
        jListComandas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDestino = new javax.swing.JComboBox();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaJuntarComandas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("CorNivel3")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPaneComandas.setName("jScrollPaneComandas"); // NOI18N

        jListComandas.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        jListComandas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jListComandas.setModel(listModelComandas);
        jListComandas.setCellRenderer(new CheckListRenderer());
        jListComandas.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jListComandas.setName("jListComandas"); // NOI18N
        jListComandas.setSelectionModel(listSelModelComandas);
        jListComandas.setVisibleRowCount(4);
        jScrollPaneComandas.setViewportView(jListComandas);
        /*
        * JList contendo elementos JCheckBox
        * ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
        * "Add a mouse listener to handle changing selection"
        *
        * Fonte: http://helpdesk.objects.com.au/java/how-do-add-a-checkbox-to-items-in-a-jlist
        */
        jListComandas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent event) {
                JList list = (JList) event.getSource();

                // Get index of item clicked
                int index = list.locationToIndex(event.getPoint());
                CheckListItem item = (CheckListItem) list.getModel().getElementAt(index);

                // Toggle selected state
                item.setSelected(! item.isSelected());

                // Repaint cell
                list.repaint(list.getCellBounds(index, index));
            }
        });

        jLabel1.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBoxDestino.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jComboBoxDestino.setModel(comboBoxModelDestino);
        jComboBoxDestino.setName("jComboBoxDestino"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaJuntarComandas.class, this);
        bOk.setAction(actionMap.get("confirmarUniao")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setMaximumSize(new java.awt.Dimension(96, 25));
        bOk.setMinimumSize(new java.awt.Dimension(96, 25));
        bOk.setName("bOk"); // NOI18N
        bOk.setPreferredSize(new java.awt.Dimension(96, 25));

        bCancelar.setAction(actionMap.get("cancelarUniao")); // NOI18N
        bCancelar.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setMaximumSize(new java.awt.Dimension(96, 25));
        bCancelar.setMinimumSize(new java.awt.Dimension(96, 25));
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.setPreferredSize(new java.awt.Dimension(96, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDestino, 0, 339, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneComandas, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main( String args[] )
//    {
//        java.awt.EventQueue.invokeLater( new Runnable()
//        {
//            public void run()
//            {
//                TelaJuntarComandas dialog = new TelaJuntarComandas( new javax.swing.JFrame(), true );
//                dialog.addWindowListener( new java.awt.event.WindowAdapter()
//                {
//                    public void windowClosing( java.awt.event.WindowEvent e )
//                    {
//                        System.exit( 0 );
//                    }
//                } );
//                dialog.setVisible( true );
//            }
//        } );
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox jComboBoxDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jListComandas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneComandas;
    // End of variables declaration//GEN-END:variables
}
