/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaDespesas.java
 *
 * Created on 08/09/2010, 15:16:16
 */
package sigeve;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Paulo Henrique
 */
public class TelaDespesas
    extends javax.swing.JDialog
    implements KeyListener
{
    boolean despesaRealizada;
    float valor;
    String descricao;
    SigeveView sv;

    /** Creates new form TelaDespesas */
    public TelaDespesas( SigeveView parent, boolean modal )
    {
        super( parent.getFrame(), modal );
        initComponents();
        adicionarKeyListeners();
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );

        sv = parent;
    }

    private void adicionarKeyListeners()
    {
        bCancelar.addKeyListener( this );
        bOk.addKeyListener( this );
        ftfValor.addKeyListener( this );
        tfDescricao.addKeyListener( this );
    }

    @Action
    public void cancelarDespesa()
    {
        despesaRealizada = false;
        dispose();
    }

    @Action
    public void confirmarDespesa()
    {
        if ( valor > 0 && !descricao.isEmpty() )
        {
            despesaRealizada = true;
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog( jPanel1,
                "Despesa inválida. Tente novamente.",
                "Despesas diárias",
                JOptionPane.WARNING_MESSAGE);
        }
    }

    public String getDescricao()
    {
        return descricao;
    }

    public float getValor()
    {
        return valor;
    }

    public boolean foiDespesaRealizada()
    {
        return despesaRealizada;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lDesconto = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        ftfValor = new javax.swing.JFormattedTextField();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaDespesas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(resourceMap.getColor("CorNivel3")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        lDesconto.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lDesconto.setText(resourceMap.getString("lDesconto.text")); // NOI18N
        lDesconto.setName("lDesconto"); // NOI18N

        lTotal.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lTotal.setText(resourceMap.getString("lTotal.text")); // NOI18N
        lTotal.setName("lTotal"); // NOI18N

        tfDescricao.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        tfDescricao.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfDescricao.setText(resourceMap.getString("tfDescricao.text")); // NOI18N
        tfDescricao.setName("tfDescricao"); // NOI18N
        tfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoActionPerformed(evt);
            }
        });
        tfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescricaoFocusLost(evt);
            }
        });

        ftfValor.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        ftfValor.setText(resourceMap.getString("ftfValor.text")); // NOI18N
        ftfValor.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        ftfValor.setName("ftfValor"); // NOI18N
        ftfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfValorActionPerformed(evt);
            }
        });
        ftfValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftfValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfValorFocusLost(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaDespesas.class, this);
        bOk.setAction(actionMap.get("confirmarDespesa")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setMaximumSize(new java.awt.Dimension(96, 25));
        bOk.setMinimumSize(new java.awt.Dimension(96, 25));
        bOk.setName("bOk"); // NOI18N
        bOk.setPreferredSize(new java.awt.Dimension(96, 25));

        bCancelar.setAction(actionMap.get("cancelarDespesa")); // NOI18N
        bCancelar.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setMaximumSize(new java.awt.Dimension(96, 25));
        bCancelar.setMinimumSize(new java.awt.Dimension(96, 25));
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.setPreferredSize(new java.awt.Dimension(96, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTotal)
                            .addComponent(lDesconto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(ftfValor, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDesconto)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotal)
                    .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfValorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ftfValorActionPerformed
    {//GEN-HEADEREND:event_ftfValorActionPerformed
//        try
//        {
//            sv.ajustarCampoParaMoeda( evt );
//            valor = sv.nfMoeda.parse( ftfValor.getText() ).floatValue();
            if ( valor < 0 )
            {
                JOptionPane.showMessageDialog( sv.getComponent(),
                    "A despesa não pode ter valor negativo. Tente novamente.",
                    "Despesas diárias",
                    JOptionPane.WARNING_MESSAGE );
                ftfValor.setText( "" );
                ftfValor.grabFocus();
            }
            else
                bOk.grabFocus();
//        }
//        catch ( ParseException ex )
//        {
//            Logger.getLogger( TelaDarDesconto.class.getName() ).log( Level.SEVERE, null, ex );
//            JOptionPane.showMessageDialog(
//                sv.getComponent(),
//                "Alerta! Ocorreu um erro ao informar a despesa. Informe ao responsável.",
//                "Despesas diárias",
//                JOptionPane.WARNING_MESSAGE);
//        }
}//GEN-LAST:event_ftfValorActionPerformed

    private void tfDescricaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfDescricaoActionPerformed
    {//GEN-HEADEREND:event_tfDescricaoActionPerformed
        ftfValor.grabFocus();
    }//GEN-LAST:event_tfDescricaoActionPerformed

    private void ftfValorFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ftfValorFocusLost
    {//GEN-HEADEREND:event_ftfValorFocusLost
        sv.ajustarCampoParaMoeda( evt );
        try
        {
            valor = sv.nfMoeda.parse( ftfValor.getText() ).floatValue();
        }
        catch ( ParseException ex )
        {
            Logger.getLogger( TelaDespesas.class.getName() ).log( Level.SEVERE, null, ex );
        }
    }//GEN-LAST:event_ftfValorFocusLost

    private void ftfValorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ftfValorFocusGained
    {//GEN-HEADEREND:event_ftfValorFocusGained
        try
        {
            if ( !ftfValor.getText().isEmpty() )
                ftfValor.setText(
                    sv.nf2d.format(
                    sv.nfMoeda.parse(
                    ftfValor.getText() ) ) );
        }
        catch ( ParseException ex )
        {
            Logger.getLogger( SigeveView.class.getName() ).log( Level.OFF, null, ex );
        }
        finally
        {
            ftfValor.selectAll();
        }
    }//GEN-LAST:event_ftfValorFocusGained

    private void tfDescricaoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tfDescricaoFocusLost
    {//GEN-HEADEREND:event_tfDescricaoFocusLost
        descricao = tfDescricao.getText();
    }//GEN-LAST:event_tfDescricaoFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDesconto;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables

    public void keyTyped( KeyEvent e )
    {
        //throw new UnsupportedOperationException( "Not supported yet." );
    }

    public void keyPressed( KeyEvent e )
    {
        if ( e.getKeyCode() == KeyEvent.VK_ESCAPE )
            cancelarDespesa();
    }

    public void keyReleased( KeyEvent e )
    {
        //throw new UnsupportedOperationException( "Not supported yet." );
    }
}
