/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaDarDesconto.java
 *
 * Created on 07/09/2010, 12:43:04
 */
package sigeve;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Paulo Henrique
 */
public class TelaDarDesconto
    extends javax.swing.JDialog
    implements KeyListener
{
    private float total;
    private float descontoDado = 0;
    private float descontoSugerido;
    private float novoTotal;
    SigeveView sv;

    /** Creates new form TelaDarDesconto
     * 
     * @param parent
     * @param modal
     * @param total
     */
    public TelaDarDesconto( SigeveView parent, boolean modal, float total )
    {
        super( parent.getFrame(), modal );
        initComponents();
        adicionarKeyListeners();
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );

        sv = parent;
        this.total = total;
    }

    private void adicionarKeyListeners()
    {
        bCancelar.addKeyListener( this );
        bOk.addKeyListener( this );
        ftfDesconto.addKeyListener( this );
        ftfNovoTotal.addKeyListener( this );
    }

    @Action
    public void cancelarDesconto()
    {
        dispose();
    }
    
    @Action
    public void confirmarDesconto()
    {
        descontoDado = descontoSugerido;
        dispose();
    }

    public float getDesconto()
    {
        return descontoDado;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lPreencha = new javax.swing.JLabel();
        lDesconto = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        ftfDesconto = new javax.swing.JFormattedTextField();
        ftfNovoTotal = new javax.swing.JFormattedTextField();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaDarDesconto.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(resourceMap.getColor("CorNivel3")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        lPreencha.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lPreencha.setText(resourceMap.getString("lPreencha.text")); // NOI18N
        lPreencha.setName("lPreencha"); // NOI18N

        lDesconto.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lDesconto.setText(resourceMap.getString("lDesconto.text")); // NOI18N
        lDesconto.setName("lDesconto"); // NOI18N

        lTotal.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lTotal.setText(resourceMap.getString("lTotal.text")); // NOI18N
        lTotal.setName("lTotal"); // NOI18N

        ftfDesconto.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        ftfDesconto.setText(resourceMap.getString("ftfDesconto.text")); // NOI18N
        ftfDesconto.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        ftfDesconto.setName("ftfDesconto"); // NOI18N
        ftfDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDescontoActionPerformed(evt);
            }
        });
        ftfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftfDescontoKeyReleased(evt);
            }
        });

        ftfNovoTotal.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        ftfNovoTotal.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        ftfNovoTotal.setName("ftfNovoTotal"); // NOI18N
        ftfNovoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfNovoTotalActionPerformed(evt);
            }
        });
        ftfNovoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftfNovoTotalKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaDarDesconto.class, this);
        bOk.setAction(actionMap.get("confirmarDesconto")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setMaximumSize(new java.awt.Dimension(96, 25));
        bOk.setMinimumSize(new java.awt.Dimension(96, 25));
        bOk.setName("bOk"); // NOI18N
        bOk.setPreferredSize(new java.awt.Dimension(96, 25));

        bCancelar.setAction(actionMap.get("cancelarDesconto")); // NOI18N
        bCancelar.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setMaximumSize(new java.awt.Dimension(96, 25));
        bCancelar.setMinimumSize(new java.awt.Dimension(96, 25));
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.setPreferredSize(new java.awt.Dimension(96, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPreencha)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTotal)
                            .addComponent(lDesconto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(ftfNovoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPreencha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDesconto)
                    .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotal)
                    .addComponent(ftfNovoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfDescontoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ftfDescontoActionPerformed
    {//GEN-HEADEREND:event_ftfDescontoActionPerformed
        try
        {
            sv.ajustarCampoParaMoeda( evt );
            descontoSugerido = sv.nfMoeda.parse( ftfDesconto.getText() ).floatValue();
            novoTotal = total - descontoSugerido;
            if ( descontoSugerido < 0 || novoTotal < 0 )
            {
                JOptionPane.showMessageDialog( sv.getComponent(), 
                    "Desconto inválido. Tente novamente.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
                ftfDesconto.setText( "" );
                ftfNovoTotal.setText( "" );
                ftfDesconto.grabFocus();
            }
            else
            {
                ftfNovoTotal.setText( sv.nfMoeda.format( novoTotal ) );
                confirmarDesconto();
            }
        }
        catch ( ParseException ex )
        {
            Logger.getLogger( TelaDarDesconto.class.getName() ).log( Level.SEVERE, null, ex );
        }
    }//GEN-LAST:event_ftfDescontoActionPerformed

    private void ftfNovoTotalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ftfNovoTotalActionPerformed
    {//GEN-HEADEREND:event_ftfNovoTotalActionPerformed
        try
        {
            sv.ajustarCampoParaMoeda( evt );
            novoTotal = sv.nfMoeda.parse( ftfNovoTotal.getText() ).floatValue();
            descontoSugerido = total - novoTotal;
            if ( novoTotal > total || novoTotal < 0 )
            {
                JOptionPane.showMessageDialog( sv.getComponent(),
                    "Desconto inválido. Tente novamente.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
                ftfDesconto.setText( "" );
                ftfNovoTotal.setText( "" );
                ftfNovoTotal.grabFocus();
            }
            else
            {
                ftfDesconto.setText( sv.nfMoeda.format( descontoSugerido ) );
                confirmarDesconto();
            }
        }
        catch ( ParseException ex )
        {
            Logger.getLogger( TelaDarDesconto.class.getName() ).log( Level.SEVERE, null, ex );
        }
    }//GEN-LAST:event_ftfNovoTotalActionPerformed

    private void ftfDescontoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ftfDescontoKeyReleased
    {//GEN-HEADEREND:event_ftfDescontoKeyReleased
        String strTecla = Character.toString( evt.getKeyChar() );
        int intCodigoTecla = evt.getKeyCode();
        boolean houveDelecao = ( intCodigoTecla == KeyEvent.VK_BACK_SPACE || intCodigoTecla == KeyEvent.VK_DELETE );

        if( strTecla.matches( "\\p{Print}" ) || houveDelecao )
        {
            if ( strTecla.matches( "[0-9\\,]" ) || houveDelecao )
            {
                String strDesconto = ftfDesconto.getText();
                if ( strDesconto.isEmpty() )
                    descontoSugerido = 0;
                else
                {
                    try
                    {
                        descontoSugerido = sv.nf2d.parse( strDesconto ).floatValue();
                        novoTotal = total - descontoSugerido;
                        ftfNovoTotal.setText( sv.nfMoeda.format( novoTotal ) );
                    }
                    catch ( ParseException ex )
                    {
                        Logger.getLogger( TelaFecharComanda.class.getName() ).log( Level.SEVERE, null, ex );
                    }
                }
            }
        }
    }//GEN-LAST:event_ftfDescontoKeyReleased

    private void ftfNovoTotalKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ftfNovoTotalKeyReleased
    {//GEN-HEADEREND:event_ftfNovoTotalKeyReleased
        String strTecla = Character.toString( evt.getKeyChar() );
        int intCodigoTecla = evt.getKeyCode();
        boolean houveDelecao = ( intCodigoTecla == KeyEvent.VK_BACK_SPACE || intCodigoTecla == KeyEvent.VK_DELETE );

        if( strTecla.matches( "\\p{Print}" ) || houveDelecao )
        {
            if ( strTecla.matches( "[0-9\\,]" ) || houveDelecao )
            {
                String strNovoTotal = ftfNovoTotal.getText();
                if ( strNovoTotal.isEmpty() )
                    novoTotal = 0;
                else
                {
                    try
                    {
                        novoTotal = sv.nf2d.parse( strNovoTotal ).floatValue();
                        descontoSugerido = total - novoTotal;
                        ftfDesconto.setText( sv.nfMoeda.format( descontoSugerido ) );
                    }
                    catch ( ParseException ex )
                    {
                        Logger.getLogger( TelaFecharComanda.class.getName() ).log( Level.SEVERE, null, ex );
                    }
                }
            }
        }
    }//GEN-LAST:event_ftfNovoTotalKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main( String args[] )
//    {
//        java.awt.EventQueue.invokeLater( new Runnable()
//        {
//            public void run()
//            {
//                TelaDarDesconto dialog = new TelaDarDesconto( new javax.swing.JFrame(), true );
//                dialog.addWindowListener( new java.awt.event.WindowAdapter()
//                {
//                    public void windowClosing( java.awt.event.WindowEvent e )
//                    {
//                        System.exit( 0 );
//                    }
//                } );
//                dialog.setVisible( true );
//            }
//        } );
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JFormattedTextField ftfDesconto;
    private javax.swing.JFormattedTextField ftfNovoTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDesconto;
    private javax.swing.JLabel lPreencha;
    private javax.swing.JLabel lTotal;
    // End of variables declaration//GEN-END:variables

    public void keyTyped( KeyEvent e )
    {
        //throw new UnsupportedOperationException( "Not supported yet." );
    }

    public void keyPressed( KeyEvent e )
    {
        if ( e.getKeyCode() == KeyEvent.VK_ESCAPE )
            cancelarDesconto();
    }

    public void keyReleased( KeyEvent e )
    {
        //throw new UnsupportedOperationException( "Not supported yet." );
    }
}
