/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaExportarTabelas.java
 *
 * Created on 07/02/2011, 21:38:34
 */

package sigeve;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Paulo Henrique
 */
public class TelaExportarTabelas extends javax.swing.JDialog {

    BancoDeDados bd;
    
    /** Creates new form TelaExportarTabelas */
    public TelaExportarTabelas(SigeveView parent, boolean modal, BancoDeDados bd) {
        super( parent.getFrame(), modal );
        initComponents();
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        this.bd = bd;
    }

    @Action
    public void cancelar()
    {
        dispose();
    }
    
    @Action
    public void confirmar()
    {
        try
        {
            if ( cbPedidos.isSelected() ) bd.exportarPedidos();
            if ( cbComandas.isSelected() ) bd.exportarComandas();
            if ( cbJornadas.isSelected() ) bd.exportarJornadas();
            if ( cbLojas.isSelected() ) bd.exportarLojas();
            if ( cbTurnos.isSelected() ) bd.exportarTurnos();
            if ( cbTempo.isSelected() ) bd.exportarTempo();
            if ( cbFuncionarios.isSelected() ) bd.exportarFuncionarios();
            if ( cbFuncionariosJornadas.isSelected() ) bd.exportarFuncionariosJornadas();
            if ( cbDespesas.isSelected() ) bd.exportarDespesas();
            if ( cbProdutos.isSelected() ) bd.exportarProdutos();
            if ( cbCategorias.isSelected() ) bd.exportarCategorias();
            JOptionPane.showMessageDialog( 
                jPanel1, 
                "Tabela(s) do Banco de Dados exportada(s) com sucesso.",
                "Exportação do Banco de Dados",
                JOptionPane.PLAIN_MESSAGE);
        }
        catch ( SQLException ex )
        {
            Logger.getLogger( TelaExportarTabelas.class.getName() ).log( 
                Level.SEVERE, 
                "Erro ao exportar a(s) tabela(s) selecionada(s).", 
                ex );
        }
        finally
        {
            dispose();
        }
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pTebelas = new javax.swing.JPanel();
        cbPedidos = new javax.swing.JCheckBox();
        cbComandas = new javax.swing.JCheckBox();
        cbJornadas = new javax.swing.JCheckBox();
        cbDespesas = new javax.swing.JCheckBox();
        cbFuncionarios = new javax.swing.JCheckBox();
        cbFuncionariosJornadas = new javax.swing.JCheckBox();
        cbTempo = new javax.swing.JCheckBox();
        cbTurnos = new javax.swing.JCheckBox();
        cbLojas = new javax.swing.JCheckBox();
        cbProdutos = new javax.swing.JCheckBox();
        cbCategorias = new javax.swing.JCheckBox();
        cbTodas = new javax.swing.JCheckBox();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaExportarTabelas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        pTebelas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        pTebelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pTebelas.setName("pTebelas"); // NOI18N

        cbPedidos.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbPedidos.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbPedidos.setText(resourceMap.getString("cbPedidos.text")); // NOI18N
        cbPedidos.setName("cbPedidos"); // NOI18N
        cbPedidos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbComandas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbComandas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbComandas.setText(resourceMap.getString("cbComandas.text")); // NOI18N
        cbComandas.setName("cbComandas"); // NOI18N
        cbComandas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbJornadas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbJornadas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbJornadas.setText(resourceMap.getString("cbJornadas.text")); // NOI18N
        cbJornadas.setName("cbJornadas"); // NOI18N
        cbJornadas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbDespesas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbDespesas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbDespesas.setText(resourceMap.getString("cbDespesas.text")); // NOI18N
        cbDespesas.setName("cbDespesas"); // NOI18N
        cbDespesas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbFuncionarios.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbFuncionarios.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbFuncionarios.setText(resourceMap.getString("cbFuncionarios.text")); // NOI18N
        cbFuncionarios.setName("cbFuncionarios"); // NOI18N
        cbFuncionarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbFuncionariosJornadas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbFuncionariosJornadas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbFuncionariosJornadas.setText(resourceMap.getString("cbFuncionariosJornadas.text")); // NOI18N
        cbFuncionariosJornadas.setName("cbFuncionariosJornadas"); // NOI18N
        cbFuncionariosJornadas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbTempo.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbTempo.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbTempo.setText(resourceMap.getString("cbTempo.text")); // NOI18N
        cbTempo.setName("cbTempo"); // NOI18N
        cbTempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbTurnos.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbTurnos.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbTurnos.setText(resourceMap.getString("cbTurnos.text")); // NOI18N
        cbTurnos.setName("cbTurnos"); // NOI18N
        cbTurnos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbLojas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbLojas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbLojas.setText(resourceMap.getString("cbLojas.text")); // NOI18N
        cbLojas.setName("cbLojas"); // NOI18N
        cbLojas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbProdutos.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbProdutos.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbProdutos.setText(resourceMap.getString("cbProdutos.text")); // NOI18N
        cbProdutos.setName("cbProdutos"); // NOI18N
        cbProdutos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbCategorias.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbCategorias.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbCategorias.setText(resourceMap.getString("cbCategorias.text")); // NOI18N
        cbCategorias.setName("cbCategorias"); // NOI18N
        cbCategorias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxStateChanged(evt);
            }
        });

        cbTodas.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        cbTodas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        cbTodas.setText(resourceMap.getString("cbTodas.text")); // NOI18N
        cbTodas.setName("cbTodas"); // NOI18N
        cbTodas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbTodasStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pTebelasLayout = new javax.swing.GroupLayout(pTebelas);
        pTebelas.setLayout(pTebelasLayout);
        pTebelasLayout.setHorizontalGroup(
            pTebelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTebelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTebelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFuncionarios)
                    .addComponent(cbJornadas)
                    .addComponent(cbDespesas)
                    .addComponent(cbComandas)
                    .addComponent(cbPedidos)
                    .addComponent(cbFuncionariosJornadas))
                .addGap(18, 18, 18)
                .addGroup(pTebelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTempo)
                    .addComponent(cbTurnos)
                    .addComponent(cbProdutos)
                    .addComponent(cbLojas)
                    .addComponent(cbCategorias)
                    .addComponent(cbTodas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTebelasLayout.setVerticalGroup(
            pTebelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTebelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTebelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pTebelasLayout.createSequentialGroup()
                        .addComponent(cbTempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTurnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLojas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTodas))
                    .addGroup(pTebelasLayout.createSequentialGroup()
                        .addComponent(cbPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbComandas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJornadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDespesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFuncionarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFuncionariosJornadas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaExportarTabelas.class, this);
        bOk.setAction(actionMap.get("confirmar")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setName("bOk"); // NOI18N
        bOk.setPreferredSize(new java.awt.Dimension(85, 25));

        bCancelar.setAction(actionMap.get("cancelar")); // NOI18N
        bCancelar.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setName("bCancelar"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTebelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTebelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTodasStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_cbTodasStateChanged
    {//GEN-HEADEREND:event_cbTodasStateChanged
        if ( cbTodas.isSelected() )
        {
            cbPedidos.setSelected( true );
            cbComandas.setSelected( true );
            cbJornadas.setSelected( true );
            cbDespesas.setSelected( true );
            cbFuncionarios.setSelected( true );
            cbFuncionariosJornadas.setSelected( true );
            cbLojas.setSelected( true );
            cbTurnos.setSelected( true );
            cbTempo.setSelected( true );
            cbProdutos.setSelected( true );
            cbCategorias.setSelected( true );
        }
    }//GEN-LAST:event_cbTodasStateChanged

    private void jCheckBoxStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jCheckBoxStateChanged
    {//GEN-HEADEREND:event_jCheckBoxStateChanged
        JCheckBox cb = (JCheckBox) evt.getSource();
        if ( !cb.isSelected() )
        {
            cbTodas.setSelected( false );
        }
    }//GEN-LAST:event_jCheckBoxStateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JCheckBox cbCategorias;
    private javax.swing.JCheckBox cbComandas;
    private javax.swing.JCheckBox cbDespesas;
    private javax.swing.JCheckBox cbFuncionarios;
    private javax.swing.JCheckBox cbFuncionariosJornadas;
    private javax.swing.JCheckBox cbJornadas;
    private javax.swing.JCheckBox cbLojas;
    private javax.swing.JCheckBox cbPedidos;
    private javax.swing.JCheckBox cbProdutos;
    private javax.swing.JCheckBox cbTempo;
    private javax.swing.JCheckBox cbTodas;
    private javax.swing.JCheckBox cbTurnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pTebelas;
    // End of variables declaration//GEN-END:variables

}
