/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaComandasFechadas.java
 *
 * Created on 14/11/2010, 20:14:57
 */

package sigeve;

import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Paulo Henrique
 */
public class TelaComandasFechadas extends javax.swing.JDialog {

    private BancoDeDados bd;
    private SigeveView sv;
    private Jornada jornada;
    
    /** Creates new form TelaComandasFechadas
     * @param parent
     * @param modal
     * @param jornada
     * @param bd
     */
    public TelaComandasFechadas(
        SigeveView parent,
        boolean modal,
        Jornada jornada,
        BancoDeDados bd )
    {
        super( parent.getFrame(), modal );
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        this.bd = bd;
        this.sv = parent;
        this.jornada = jornada;
        initComponents();
        escreverInformacoes( jornada );
    }

    private void escreverInformacoes( Jornada j )
    {
        tfCaixaAbertura.setText( sv.nfMoeda.format( j.getCaixaInicial() ) );
        tfCaixaAtual.setText( sv.nfMoeda.format( j.getCaixaFinal() ) );
        tfReforcos.setText( sv.nfMoeda.format( j.getReforcos() ) );
        tfSangrias.setText( sv.nfMoeda.format( j.getSangrias() ) );
        tfDespesas.setText( sv.nfMoeda.format( j.getDespesas() ) );
        float vendas = j.getCaixaFinal() + j.getSangrias()
            + j.getDespesas() - j.getCaixaInicial() - j.getReforcos();
        tfVendas.setText( sv.nfMoeda.format( vendas ) );
        tfCaixaAtual.setText( sv.nfMoeda.format( j.getCaixaFinal() ) );
    }

    @Action
    public void fecharTela()
    {
        dispose();
//        String justificativa = taJustificativa.getText();
//        if ( justificativa.isEmpty() )
//        {
//            JOptionPane.showMessageDialog( painelPrincipal,
//                "Faltou escrever a justificativa.",
//                "Comandas fechadas",
//                JOptionPane.WARNING_MESSAGE);
//        }
//        else
//        {
//            dispose();
//        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelResultado = new javax.swing.JPanel();
        lCaixaAbertura = new javax.swing.JLabel();
        lVendas = new javax.swing.JLabel();
        lReforcos = new javax.swing.JLabel();
        lSangrias = new javax.swing.JLabel();
        lDespesas = new javax.swing.JLabel();
        lCaixaAtual = new javax.swing.JLabel();
        tfCaixaAbertura = new javax.swing.JTextField();
        tfVendas = new javax.swing.JTextField();
        tfReforcos = new javax.swing.JTextField();
        tfSangrias = new javax.swing.JTextField();
        tfDespesas = new javax.swing.JTextField();
        tfCaixaAtual = new javax.swing.JTextField();
        painelJustificativa = new javax.swing.JPanel();
        lAviso = new javax.swing.JLabel();
        spJustificativa = new javax.swing.JScrollPane();
        taJustificativa = new javax.swing.JTextArea();
        bOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaComandasFechadas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        painelPrincipal.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        painelPrincipal.setName("painelPrincipal"); // NOI18N

        painelResultado.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        painelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("painelResultado.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("FontePadrao"))); // NOI18N
        painelResultado.setName("painelResultado"); // NOI18N

        lCaixaAbertura.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lCaixaAbertura.setText(resourceMap.getString("lCaixaAbertura.text")); // NOI18N
        lCaixaAbertura.setFocusable(false);
        lCaixaAbertura.setName("lCaixaAbertura"); // NOI18N

        lVendas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lVendas.setText(resourceMap.getString("lVendas.text")); // NOI18N
        lVendas.setFocusable(false);
        lVendas.setName("lVendas"); // NOI18N

        lReforcos.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lReforcos.setText(resourceMap.getString("lReforcos.text")); // NOI18N
        lReforcos.setFocusable(false);
        lReforcos.setName("lReforcos"); // NOI18N

        lSangrias.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lSangrias.setText(resourceMap.getString("lSangrias.text")); // NOI18N
        lSangrias.setFocusable(false);
        lSangrias.setName("lSangrias"); // NOI18N

        lDespesas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lDespesas.setText(resourceMap.getString("lDespesas.text")); // NOI18N
        lDespesas.setFocusable(false);
        lDespesas.setName("lDespesas"); // NOI18N

        lCaixaAtual.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lCaixaAtual.setText(resourceMap.getString("lCaixaAtual.text")); // NOI18N
        lCaixaAtual.setFocusable(false);
        lCaixaAtual.setName("lCaixaAtual"); // NOI18N

        tfCaixaAbertura.setBackground(resourceMap.getColor("tfCaixaAbertura.background")); // NOI18N
        tfCaixaAbertura.setEditable(false);
        tfCaixaAbertura.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfCaixaAbertura.setEnabled(false);
        tfCaixaAbertura.setFocusable(false);
        tfCaixaAbertura.setName("tfCaixaAbertura"); // NOI18N

        tfVendas.setBackground(resourceMap.getColor("tfVendas.background")); // NOI18N
        tfVendas.setEditable(false);
        tfVendas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfVendas.setEnabled(false);
        tfVendas.setFocusable(false);
        tfVendas.setName("tfVendas"); // NOI18N

        tfReforcos.setBackground(resourceMap.getColor("tfReforcos.background")); // NOI18N
        tfReforcos.setEditable(false);
        tfReforcos.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfReforcos.setEnabled(false);
        tfReforcos.setFocusable(false);
        tfReforcos.setName("tfReforcos"); // NOI18N

        tfSangrias.setBackground(resourceMap.getColor("tfSangrias.background")); // NOI18N
        tfSangrias.setEditable(false);
        tfSangrias.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfSangrias.setEnabled(false);
        tfSangrias.setFocusable(false);
        tfSangrias.setName("tfSangrias"); // NOI18N

        tfDespesas.setBackground(resourceMap.getColor("tfDespesas.background")); // NOI18N
        tfDespesas.setEditable(false);
        tfDespesas.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfDespesas.setEnabled(false);
        tfDespesas.setFocusable(false);
        tfDespesas.setName("tfDespesas"); // NOI18N

        tfCaixaAtual.setBackground(resourceMap.getColor("tfCaixaAtual.background")); // NOI18N
        tfCaixaAtual.setEditable(false);
        tfCaixaAtual.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfCaixaAtual.setEnabled(false);
        tfCaixaAtual.setFocusable(false);
        tfCaixaAtual.setName("tfCaixaAtual"); // NOI18N

        javax.swing.GroupLayout painelResultadoLayout = new javax.swing.GroupLayout(painelResultado);
        painelResultado.setLayout(painelResultadoLayout);
        painelResultadoLayout.setHorizontalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lVendas)
                    .addComponent(lReforcos)
                    .addComponent(lSangrias)
                    .addComponent(lCaixaAtual)
                    .addComponent(lCaixaAbertura)
                    .addComponent(lDespesas))
                .addGap(29, 29, 29)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfVendas)
                    .addComponent(tfReforcos)
                    .addComponent(tfSangrias)
                    .addComponent(tfCaixaAtual)
                    .addComponent(tfDespesas)
                    .addComponent(tfCaixaAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        painelResultadoLayout.setVerticalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoLayout.createSequentialGroup()
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCaixaAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCaixaAbertura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lVendas)
                    .addComponent(tfVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lReforcos)
                    .addComponent(tfReforcos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSangrias)
                    .addComponent(tfSangrias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDespesas)
                    .addComponent(tfDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCaixaAtual)
                    .addComponent(tfCaixaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelJustificativa.setBackground(resourceMap.getColor("CorNivel2")); // NOI18N
        painelJustificativa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("painelJustificativa.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("FontePadrao"))); // NOI18N
        painelJustificativa.setName("painelJustificativa"); // NOI18N

        lAviso.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        lAviso.setText(resourceMap.getString("lAviso.text")); // NOI18N
        lAviso.setName("lAviso"); // NOI18N

        spJustificativa.setName("spJustificativa"); // NOI18N

        taJustificativa.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        taJustificativa.setColumns(20);
        taJustificativa.setEditable(false);
        taJustificativa.setLineWrap(true);
        taJustificativa.setRows(2);
        taJustificativa.setEnabled(false);
        taJustificativa.setName("taJustificativa"); // NOI18N
        spJustificativa.setViewportView(taJustificativa);

        javax.swing.GroupLayout painelJustificativaLayout = new javax.swing.GroupLayout(painelJustificativa);
        painelJustificativa.setLayout(painelJustificativaLayout);
        painelJustificativaLayout.setHorizontalGroup(
            painelJustificativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJustificativaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelJustificativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spJustificativa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(lAviso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelJustificativaLayout.setVerticalGroup(
            painelJustificativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJustificativaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaComandasFechadas.class, this);
        bOk.setAction(actionMap.get("fecharTela")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setName("bOk"); // NOI18N

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelJustificativa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JLabel lAviso;
    private javax.swing.JLabel lCaixaAbertura;
    private javax.swing.JLabel lCaixaAtual;
    private javax.swing.JLabel lDespesas;
    private javax.swing.JLabel lReforcos;
    private javax.swing.JLabel lSangrias;
    private javax.swing.JLabel lVendas;
    private javax.swing.JPanel painelJustificativa;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelResultado;
    private javax.swing.JScrollPane spJustificativa;
    private javax.swing.JTextArea taJustificativa;
    private javax.swing.JTextField tfCaixaAbertura;
    private javax.swing.JTextField tfCaixaAtual;
    private javax.swing.JTextField tfDespesas;
    private javax.swing.JTextField tfReforcos;
    private javax.swing.JTextField tfSangrias;
    private javax.swing.JTextField tfVendas;
    // End of variables declaration//GEN-END:variables

}
