    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaGuardarComanda.java
 *
 * Created on 16/01/2011, 17:57:07
 */

package sigeve;

import java.awt.event.KeyEvent;
import org.jdesktop.application.Action;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import static sigeve.Constantes.*;

/**
 *
 * @author Paulo Henrique
 */
public class TelaGuardarComanda extends javax.swing.JDialog
{
    private JToggleButton[] arrayOriginal; // Array dos botões de SigeveView.
    private JToggleButton[] arrayClone; // Array dos botões desta tela.
    private BancoDeDados bd;
    private SigeveView sv;
    private boolean existePosicaoDisponivel;
    private int posicaoDisponivel;
    private int posicao;
    private String identificacao;

    /** Creates new form TelaGuardarComanda */
    public TelaGuardarComanda(SigeveView parent, boolean modal, BancoDeDados bd) 
    {
        super( parent.getFrame(), modal );
        this.bd = bd;
        this.sv = parent;
        arrayOriginal = sv.obterArrayBotoes();

        initComponents();
        construirArrays();
        nomearBotoes();

        try
        {
            existePosicaoDisponivel = bd.existePosicaoDisponivelBD();
            if ( existePosicaoDisponivel )
            {
                posicaoDisponivel = bd.obterPosicaoDisponivelBD();
            }
        }
        catch ( SQLException ex )
        {
            Logger.getLogger( TelaGuardarComanda.class.getName() ).log( Level.SEVERE, null, ex );
        }
    }

    private void nomearBotoes()
    {
        for (int cont = 0; cont <= N_BOTOES_COMANDAS; cont++)
        {
            arrayClone[cont].setText( arrayOriginal[cont].getText() );
        }
    }

    private void construirArrays()
    {
        arrayClone = new JToggleButton[N_BOTOES_COMANDAS + 1];
        arrayClone[0] = jToggleButtonComandaFantasma;
        arrayClone[1] = jToggleButtonComanda01;
        arrayClone[2] = jToggleButtonComanda02;
        arrayClone[3] = jToggleButtonComanda03;
        arrayClone[4] = jToggleButtonComanda04;
        arrayClone[5] = jToggleButtonComanda05;
        arrayClone[6] = jToggleButtonComanda06;
        arrayClone[7] = jToggleButtonComanda07;
        arrayClone[8] = jToggleButtonComanda08;
        arrayClone[9] = jToggleButtonComanda09;
        arrayClone[10] = jToggleButtonComanda10;
        arrayClone[11] = jToggleButtonComanda11;
        arrayClone[12] = jToggleButtonComanda12;
        arrayClone[13] = jToggleButtonComanda13;
        arrayClone[14] = jToggleButtonComanda14;
        arrayClone[15] = jToggleButtonComanda15;
    }

    @Action
    public void confirmar()
    {
        // Garantir que a posição esteja ocupada caso se tenha entrado um número.
        // (Já implementado no método que chama este método!)
        
        if ( ! identificacao.matches( "\\d+" ) )
        {
            posicao = posicaoDisponivel;
        }
        // Garantir que haja espaço caso se esteja criando uma nova comanda.
        if ( posicao > N_BOTOES_COMANDAS || posicao <= 0 )
        {
            JOptionPane.showMessageDialog( this,
                "A posição solicitada não é permitida, ou o número máximo de "
                + "comandas (" + N_BOTOES_COMANDAS + ") já foi alcançado.",
                "Erro ao guardar comanda",
                JOptionPane.WARNING_MESSAGE );
        }
        else
        {
            dispose();
        }
    }

    @Action
    public void cancelar()
    {
        identificacao = null;
        dispose();
    }

    public String obterIdentificacao()
    {
        return identificacao;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelClientes = new javax.swing.JPanel();
        jToggleButtonComanda01 = new javax.swing.JToggleButton();
        jToggleButtonComanda02 = new javax.swing.JToggleButton();
        jToggleButtonComanda03 = new javax.swing.JToggleButton();
        jToggleButtonComanda04 = new javax.swing.JToggleButton();
        jToggleButtonComanda05 = new javax.swing.JToggleButton();
        jToggleButtonComanda06 = new javax.swing.JToggleButton();
        jToggleButtonComanda07 = new javax.swing.JToggleButton();
        jToggleButtonComanda08 = new javax.swing.JToggleButton();
        jToggleButtonComanda09 = new javax.swing.JToggleButton();
        jToggleButtonComanda10 = new javax.swing.JToggleButton();
        jToggleButtonComanda11 = new javax.swing.JToggleButton();
        jToggleButtonComanda12 = new javax.swing.JToggleButton();
        jToggleButtonComanda13 = new javax.swing.JToggleButton();
        jToggleButtonComanda14 = new javax.swing.JToggleButton();
        jToggleButtonComanda15 = new javax.swing.JToggleButton();
        jToggleButtonComandaFantasma = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        tfIdentificacao = new javax.swing.JTextField();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getResourceMap(TelaGuardarComanda.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("CorNivel3")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanelClientes.setBackground(resourceMap.getColor("jPanelClientes.background")); // NOI18N
        jPanelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanelClientes.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("FontePadrao"))); // NOI18N
        jPanelClientes.setFont(resourceMap.getFont("jPanelClientes.font")); // NOI18N
        jPanelClientes.setName("jPanelClientes"); // NOI18N
        jPanelClientes.setPreferredSize(new java.awt.Dimension(1050, 160));

        jToggleButtonComanda01.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda01.setText(resourceMap.getString("jToggleButtonComanda01.text")); // NOI18N
        jToggleButtonComanda01.setActionCommand(resourceMap.getString("jToggleButtonComanda01.actionCommand")); // NOI18N
        jToggleButtonComanda01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda01.setContentAreaFilled(false);
        jToggleButtonComanda01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda01.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda01.setName("jToggleButtonComanda01"); // NOI18N

        jToggleButtonComanda02.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda02.setText(resourceMap.getString("jToggleButtonComanda02.text")); // NOI18N
        jToggleButtonComanda02.setActionCommand(resourceMap.getString("jToggleButtonComanda02.actionCommand")); // NOI18N
        jToggleButtonComanda02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda02.setContentAreaFilled(false);
        jToggleButtonComanda02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda02.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda02.setName("jToggleButtonComanda02"); // NOI18N

        jToggleButtonComanda03.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda03.setText(resourceMap.getString("jToggleButtonComanda03.text")); // NOI18N
        jToggleButtonComanda03.setActionCommand(resourceMap.getString("jToggleButtonComanda03.actionCommand")); // NOI18N
        jToggleButtonComanda03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda03.setContentAreaFilled(false);
        jToggleButtonComanda03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda03.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda03.setName("jToggleButtonComanda03"); // NOI18N

        jToggleButtonComanda04.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda04.setText(resourceMap.getString("jToggleButtonComanda04.text")); // NOI18N
        jToggleButtonComanda04.setActionCommand(resourceMap.getString("jToggleButtonComanda04.actionCommand")); // NOI18N
        jToggleButtonComanda04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda04.setContentAreaFilled(false);
        jToggleButtonComanda04.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda04.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda04.setName("jToggleButtonComanda04"); // NOI18N

        jToggleButtonComanda05.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda05.setText(resourceMap.getString("jToggleButtonComanda05.text")); // NOI18N
        jToggleButtonComanda05.setActionCommand(resourceMap.getString("jToggleButtonComanda05.actionCommand")); // NOI18N
        jToggleButtonComanda05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda05.setContentAreaFilled(false);
        jToggleButtonComanda05.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda05.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda05.setName("jToggleButtonComanda05"); // NOI18N

        jToggleButtonComanda06.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda06.setText(resourceMap.getString("jToggleButtonComanda06.text")); // NOI18N
        jToggleButtonComanda06.setActionCommand(resourceMap.getString("jToggleButtonComanda06.actionCommand")); // NOI18N
        jToggleButtonComanda06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda06.setContentAreaFilled(false);
        jToggleButtonComanda06.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda06.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda06.setName("jToggleButtonComanda06"); // NOI18N

        jToggleButtonComanda07.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda07.setText(resourceMap.getString("jToggleButtonComanda07.text")); // NOI18N
        jToggleButtonComanda07.setActionCommand(resourceMap.getString("jToggleButtonComanda07.actionCommand")); // NOI18N
        jToggleButtonComanda07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda07.setContentAreaFilled(false);
        jToggleButtonComanda07.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda07.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda07.setName("jToggleButtonComanda07"); // NOI18N

        jToggleButtonComanda08.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda08.setText(resourceMap.getString("jToggleButtonComanda08.text")); // NOI18N
        jToggleButtonComanda08.setActionCommand(resourceMap.getString("jToggleButtonComanda08.actionCommand")); // NOI18N
        jToggleButtonComanda08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda08.setContentAreaFilled(false);
        jToggleButtonComanda08.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda08.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda08.setName("jToggleButtonComanda08"); // NOI18N

        jToggleButtonComanda09.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda09.setText(resourceMap.getString("jToggleButtonComanda09.text")); // NOI18N
        jToggleButtonComanda09.setActionCommand(resourceMap.getString("jToggleButtonComanda09.actionCommand")); // NOI18N
        jToggleButtonComanda09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda09.setContentAreaFilled(false);
        jToggleButtonComanda09.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda09.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda09.setName("jToggleButtonComanda09"); // NOI18N

        jToggleButtonComanda10.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda10.setText(resourceMap.getString("jToggleButtonComanda10.text")); // NOI18N
        jToggleButtonComanda10.setActionCommand(resourceMap.getString("jToggleButtonComanda10.actionCommand")); // NOI18N
        jToggleButtonComanda10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda10.setContentAreaFilled(false);
        jToggleButtonComanda10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda10.setName("jToggleButtonComanda10"); // NOI18N

        jToggleButtonComanda11.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda11.setText(resourceMap.getString("jToggleButtonComanda11.text")); // NOI18N
        jToggleButtonComanda11.setActionCommand(resourceMap.getString("jToggleButtonComanda11.actionCommand")); // NOI18N
        jToggleButtonComanda11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda11.setContentAreaFilled(false);
        jToggleButtonComanda11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda11.setName("jToggleButtonComanda11"); // NOI18N

        jToggleButtonComanda12.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda12.setText(resourceMap.getString("jToggleButtonComanda12.text")); // NOI18N
        jToggleButtonComanda12.setActionCommand(resourceMap.getString("jToggleButtonComanda12.actionCommand")); // NOI18N
        jToggleButtonComanda12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda12.setContentAreaFilled(false);
        jToggleButtonComanda12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda12.setName("jToggleButtonComanda12"); // NOI18N

        jToggleButtonComanda13.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda13.setText(resourceMap.getString("jToggleButtonComanda13.text")); // NOI18N
        jToggleButtonComanda13.setActionCommand(resourceMap.getString("jToggleButtonComanda13.actionCommand")); // NOI18N
        jToggleButtonComanda13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda13.setContentAreaFilled(false);
        jToggleButtonComanda13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda13.setName("jToggleButtonComanda13"); // NOI18N

        jToggleButtonComanda14.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda14.setText(resourceMap.getString("jToggleButtonComanda14.text")); // NOI18N
        jToggleButtonComanda14.setActionCommand(resourceMap.getString("jToggleButtonComanda14.actionCommand")); // NOI18N
        jToggleButtonComanda14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda14.setContentAreaFilled(false);
        jToggleButtonComanda14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda14.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda14.setName("jToggleButtonComanda14"); // NOI18N

        jToggleButtonComanda15.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComanda15.setText(resourceMap.getString("jToggleButtonComanda15.text")); // NOI18N
        jToggleButtonComanda15.setActionCommand(resourceMap.getString("jToggleButtonComanda15.actionCommand")); // NOI18N
        jToggleButtonComanda15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButtonComanda15.setContentAreaFilled(false);
        jToggleButtonComanda15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonComanda15.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonComanda15.setName("jToggleButtonComanda15"); // NOI18N

        jToggleButtonComandaFantasma.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jToggleButtonComandaFantasma.setName("jToggleButtonComandaFantasma"); // NOI18N

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonComanda01, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jToggleButtonComanda06, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonComanda02, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jToggleButtonComanda07, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonComanda03, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jToggleButtonComanda08, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonComanda05, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jToggleButtonComanda10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jToggleButtonComanda04, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jToggleButtonComanda09, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonComanda12, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jToggleButtonComanda11, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jToggleButtonComanda13, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jToggleButtonComanda14, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jToggleButtonComanda15, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
            .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelClientesLayout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(jToggleButtonComandaFantasma, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonComanda01, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda06, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonComanda02, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda07, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonComanda03, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda08, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonComanda04, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda09, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonComanda05, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonComanda10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelClientesLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jToggleButtonComandaFantasma, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        jLabel1.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        tfIdentificacao.setBackground(resourceMap.getColor("CorNivel4")); // NOI18N
        tfIdentificacao.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        tfIdentificacao.setText(resourceMap.getString("tfIdentificacao.text")); // NOI18N
        tfIdentificacao.setName("tfIdentificacao"); // NOI18N
        tfIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdentificacaoActionPerformed(evt);
            }
        });
        tfIdentificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIdentificacaoKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sigeve.SigeveApp.class).getContext().getActionMap(TelaGuardarComanda.class, this);
        bOk.setAction(actionMap.get("confirmar")); // NOI18N
        bOk.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bOk.setText(resourceMap.getString("bOk.text")); // NOI18N
        bOk.setMaximumSize(new java.awt.Dimension(96, 25));
        bOk.setMinimumSize(new java.awt.Dimension(96, 25));
        bOk.setName("bOk"); // NOI18N
        bOk.setPreferredSize(new java.awt.Dimension(96, 25));

        bCancelar.setAction(actionMap.get("cancelar")); // NOI18N
        bCancelar.setFont(resourceMap.getFont("FontePadrao")); // NOI18N
        bCancelar.setText(resourceMap.getString("bCancelar.text")); // NOI18N
        bCancelar.setMaximumSize(new java.awt.Dimension(96, 25));
        bCancelar.setMinimumSize(new java.awt.Dimension(96, 25));
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.setPreferredSize(new java.awt.Dimension(96, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfIdentificacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdentificacaoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfIdentificacaoKeyReleased
    {//GEN-HEADEREND:event_tfIdentificacaoKeyReleased
        identificacao = tfIdentificacao.getText();
        
        for ( JToggleButton botao : arrayClone )
        {
            botao.setOpaque( false );
        }
        if ( identificacao.isEmpty() )
        {    
            arrayClone[ posicaoDisponivel ].setText(
                arrayOriginal[ posicaoDisponivel ].getText() );
        }
        // Se foi digitado um ou mais dígitos.
        else if ( identificacao.matches( "\\d+" ) )
        {
            posicao = Integer.parseInt( identificacao );
            try
            {
                if ( bd.estaPosicaoOcupadaBD( posicao ) )
                {
                    arrayClone[ posicao ].setOpaque( true );
                }
            }
            catch ( SQLException ex )
            {
                Logger.getLogger( TelaGuardarComanda.class.getName() ).log( Level.SEVERE, null, ex );
            }
        }
        // Caso a entrada tenha sido um nome.
        else if ( existePosicaoDisponivel )
        {
            arrayClone[ posicaoDisponivel ].setOpaque( true );
            arrayClone[ posicaoDisponivel ].setText(
                arrayOriginal[ posicaoDisponivel ].getText() + " " + identificacao );
        }
        jPanel1.updateUI();
    }//GEN-LAST:event_tfIdentificacaoKeyReleased

    private void tfIdentificacaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfIdentificacaoActionPerformed
    {//GEN-HEADEREND:event_tfIdentificacaoActionPerformed
        confirmar();
    }//GEN-LAST:event_tfIdentificacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JToggleButton jToggleButtonComanda01;
    private javax.swing.JToggleButton jToggleButtonComanda02;
    private javax.swing.JToggleButton jToggleButtonComanda03;
    private javax.swing.JToggleButton jToggleButtonComanda04;
    private javax.swing.JToggleButton jToggleButtonComanda05;
    private javax.swing.JToggleButton jToggleButtonComanda06;
    private javax.swing.JToggleButton jToggleButtonComanda07;
    private javax.swing.JToggleButton jToggleButtonComanda08;
    private javax.swing.JToggleButton jToggleButtonComanda09;
    private javax.swing.JToggleButton jToggleButtonComanda10;
    private javax.swing.JToggleButton jToggleButtonComanda11;
    private javax.swing.JToggleButton jToggleButtonComanda12;
    private javax.swing.JToggleButton jToggleButtonComanda13;
    private javax.swing.JToggleButton jToggleButtonComanda14;
    private javax.swing.JToggleButton jToggleButtonComanda15;
    private javax.swing.JToggleButton jToggleButtonComandaFantasma;
    private javax.swing.JTextField tfIdentificacao;
    // End of variables declaration//GEN-END:variables

}
